app:
  name: w7-cdn-cache
  env: ${APP_ENV-release}
  server: http
server:
  http:
    host: ${W7_CDN_CACHE_SERVER_HOST-0.0.0.0}
    port: ${W7_CDN_CACHE_SERVER_PORT-8000}
log:
  default:
    driver: stack
    channels:
      - file
      - console
  file:
    driver: file
    path: cdn-cache.log
    level: info
  console:
    driver: console
    level: info
database:
  default:
    driver: sqlite
    db_name: ${SQLITE_DIR}cdn-cache.db
    charset: utf8mb4
    show_sql: false
    prefix: ims_
    logger: db
setting:
  oauth_token: ${OAUTH_TOKEN-rogtdpxguk}
cache:
  cleanup:
    enabled: ${CACHE_CLEANUP_ENABLED-true}
    queue_dir: ${CACHE_CLEANUP_QUEUE_DIR-}
